// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:0676242f-fb80-4314-b55b-07e7be2707e8",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_4Wtoj29Jz",
    "aws_user_pools_web_client_id": "4e7mdtrs0tfohc3ll4i12od0jn",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://f7vei5anmvadhel4viae5zhnnu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
